### ISSUE TITLE
Feature Request: Add option to pretty print / format Json output

### ISSUE THREAD

**Issue by Michael-Marshall** [cake-contrib/Cake.Json#16]
It would be really nice if we had the option to pretty print (indent) the json serialised output - especially when using SerializeJsonToFile.
Use Case - I am using Cake.Json to update the version number of a DotNetCore application and it would nice if after running the build did not have to manually pretty print my project.json.
This could be achieved by adding an optional parameter to SerializeJsonToFile and calling JsonConvert.SerializeObject with Indent.

**Comment by pascalberger** [comment]
Theres a PR available here: #7

**Comment by johnnyasantoss** [comment]
This has already been implemented 😄 
Here are the aliases:
[SerializeJsonPretty<T>][doc-1]
[SerializeJsonPrettyFile<T>][doc-2]

[doc-1]: http://cakebuild.net/api/Cake.Json/JsonAliases/1FF9BAC1
[doc-2]: http://cakebuild.net/api/Cake.Json/JsonAliases/F0E07094

**Comment by gep13** [comment]
Agreed, looks like this has already shipped.
