### ISSUE TITLE
Version 2.0.28 broke cake build script

### ISSUE THREAD

**Issue by saberone** [cake-contrib/Cake.Json#23]
Since this morning our build script kept giving us the following error.

```##[error]Error: Failed to install addin 'Cake.Json'.```

After investigating we saw that Cake.Json 2.0.28 was released. After we forced a specific version of Cake.Json it worked again. We used the last known working version like so: 

```#addin nuget:?package=Cake.Json&version=1.0.2.13```

**Comment by gep13** [comment]
I am going to go ahead and close this out, as I think this has been addressed.  Feel free to comment again if still an issue.
