### ISSUE TITLE
Release to fix Cake.Core and Newtonsoft.Json

### ISSUE THREAD

**Issue by Diogomrol** [cake-contrib/Cake.Json#40]
Hi there,

I am aware that Cake.Core and Newtonsoft.Json versions have been bumped already to remove the warnings, but there was not any release yet.

@gep13 do you have plans to do this anytime soon?

Thank you!

**Comment by gep13** [comment]
@Diogomrol yes.  Life sort of got in the way.  Going to be attempting to do a 4.0.0 release tonight, which should have the latest "bits" in it.

Let me know if there are any issues once it is released.

**Comment by Diogomrol** [comment]
@gep13 good timing, the version 0.34.1 is out just a few days ago :D

**Comment by gep13** [comment]
>@Diogomrol said...
good timing, the version 0.34.1 is out just a few days ago :D

There were no breaking changes in the 0.34.x releases of Cake.  As a result, the recommended version of Cake to compile addins against is 0.33.0.
