### ISSUE TITLE
Compatibility warning when running against Cake v1.0.0

### ISSUE THREAD

**Issue by wazzamatazz** [cake-contrib/Cake.Json#49]
## Expected Behavior

When using Cake.Json in a build script that uses Cake 1.0.0, there should not be any compatibility warnings displayed.

## Current Behavior

Using the latest version (5.2.0) of Cake.Json with Cake 1.0.0 causes a warning message during build:

```
The assembly 'Cake.Json, Version=5.2.0.0, Culture=neutral, PublicKeyToken=null' is referencing an older version of Cake.Core (0.35.0). 
For best compatibility it should target Cake.Core version 1.0.0.
```

## Possible Solution

Update Cake.Json to target Cake 1.0.0.

## Context

This issue has no real impact beyond a mildly annoying warning message, as there do not seem to be any actual compatibility issues.

**Comment by gep13** [comment]
@wazzamatazz :wave:

This is on my list of addins to get updated to use Cake 1.0.0.  Should hopefully get to this later this week.
