### ISSUE TITLE
#addin "Cake.Json" does not work

### ISSUE THREAD

**Issue by DrKoch** [cake-contrib/Cake.Json#6]
I get this error from a Cake run form  the line
"#addin "Cake.Json"

> Unable to locate any assemblies under D:/GitBase/CombyteVisSolutions/CakeTools/Addins/Cake.Json
> D:\GitBase\CombyteVisSolutions\CakeTools\Cake\Cake.exe : Error: Cake.Core.CakeException: Failed to install addin 'Cake.Json'.

The folder ./Addins/Cake.Json contains only the file Cake.Json.nupkg, no further files or folders

**Comment by GeertvanHorrik** [comment]
Seems to work for me now.

**Comment by gep13** [comment]
Going to go ahead and close this, as I think it has been resolved.
