### ISSUE TITLE
Redundant nuspec dependencies 

### ISSUE THREAD

**Issue by devlead** [cake-contrib/Cake.Json#9]
The [Cake.Json.nuspec](https://github.com/Redth/Cake.Json/blob/master/Cake.Json.nuspec#L19) adds dependency to Cake.Core and Newtonsoft.Json, ad Cake.Core is distributed with Cake and [Newtonsoft.Json](https://github.com/Redth/Cake.Json/blob/master/Cake.Json.nuspec#L28) is distrubuted with this nuget this isn't necessary.
Also results in Cake.Core & Newtonsoft.Json behing downloaded to the addin folder.

**Comment by pascalberger** [comment]
This would be fixed with #19

**Comment by gep13** [comment]
@devlead @pascalberger for the most part, with the transition to the new csproj format, this problem has been corrected, so I am going to go ahead and close this issue out, and we can open another one, if you feel that there is still an issue.
